Add command to run scheduled events
devinit/ddw-analyst-ui pull request #175
Opened 2020-05-22 17:22 UTC by davidebukali

#161

2020-05-28 15:06 UTC, edwinmp commented
That was a bit confusing, probably cos it had function names in it ... hehe

Anyway, this is the behaviour I expect.

1. Get all scheduled events that are `enabled`
2. For each scheduled event, check if they have a run instance that has `status = pending` with a start date/time that's less than the current date/time.
3. Before you run each instance, check whether there's a different instance that has a `status = running` - if so, set this one's status to `skipped` and set `ended_at` to current date/time.
4. If none are found in step 3, trigger each run instance that's found on steps 2
5. Within each running script (you'll need to update them - don't think they're that many yet - https://ddw.devinit.org/api/list_update_scripts - at least update the FTS one for staters), check if there are running instances for it that fit the current date/time, and update them at each relevant stage i.e. `running`, `complete`, `errored` e.t.c
6. After running, check if scheduled event is recursive - if so, calculate the next run time and create a new run instance for that future date/time with a `status = pending`

2020-06-01 19:18 UTC, akmiller01 requested changes
Looks good, David. And starts up fine on my end. Would you be able to add something to `data/tests.py` to test this? I included a test shell script that just echos here https://github.com/devinit/ddw-analyst-ui/blob/develop/data_updates/test_stream.sh

2020-06-01 19:18 UTC, akmiller01 commented on core/models.py
>          ('e', 'Erroed'),
Outside of your code, but just spotted this typo. `Errored`

2020-06-10 06:37 UTC, edwinmp commented
@davidebukali what's pending on this? Could you have it all resolved so we can merge it in.

2020-06-10 11:56 UTC, akmiller01 commented
> @davidebukali what's pending on this? Could you have it all resolved so we can merge it in.

My change requested is for David to add an automated test to `data/tests.py`

2020-06-10 17:55 UTC, akmiller01 requested changes

2020-06-10 20:34 UTC, akmiller01 approved these changes
Tests passing, looks good!

2020-06-10 20:36 UTC, merged