Feature/paginated fetching scheduled events
devinit/ddw-analyst-ui pull request #212
Opened 2020-07-04 13:00 UTC by davidebukali

#206

2020-07-07 12:08 UTC, edwinmp requested changes

2020-07-07 12:20 UTC, edwinmp reviewed
Could you please fetch them sorted by descending start date (as they were before).

Also add loading indicators for when data is being fetched. There are already tables that have this, so customise from those.

2020-07-07 14:07 UTC, davidebukali commented on frontend/src/components/ScheduledEventsRunHistoryTableCard/ScheduledEventsRunHistoryTableCard.tsx
> +        console.log(`Page count is ${pageCount}`);
Yes, removed ...

2020-07-07 14:07 UTC, davidebukali commented on frontend/src/components/ScheduledEventsTable/ScheduledEventsTable.tsx
> +    }
Updated

2020-07-09 06:31 UTC, edwinmp approved these changes
LGTM!

2020-07-09 06:41 UTC, merged