Feature/error proof endpoints
devinit/ddw-analyst-ui pull request #481
Opened 2021-03-19 14:51 UTC by ThatcherK

2021-03-22 10:12 UTC, edwinmp reviewed
Your branch clearly needs a rebase ... it's currently cluttered up with commits from other sources, so let me know when you've cleaned it up.

2021-03-23 08:47 UTC, edwinmp requested changes

2021-03-23 10:33 UTC, ThatcherK commented on core/views.py
> +        except Operation.DoesNotExist:
Sure it does not

2021-03-25 08:19 UTC, edwinmp submitted a review, later dismissed

2021-03-25 08:21 UTC, edwinmp approved these changes

2021-03-25 08:36 UTC, merged