Feature/duplicate step
devinit/ddw-analyst-ui pull request #484
Opened 2021-03-29 06:54 UTC by ThatcherK

2021-03-29 15:05 UTC, edwinmp requested changes
Good work. Some of my comments may be obsolete as I made a tiny change which I'm sure has broken the styling. Well, there's a comment on that somewhere as well.

2021-03-30 06:22 UTC, edwinmp commented on frontend/src/components/OperationSteps/OperationSteps.tsx
> +                  </div>
Your styling seems to only hide the buttons, but the entire row is always showing, which leaves extra padding when one isn't hovering on the button. Update the styling to show/hide the entire actions row, not just the buttons.


How it is:
![image](https://user-images.githubusercontent.com/5672438/112942776-516a0c80-9139-11eb-90b2-604ef40b1aa7.png)


How it should be:
![image](https://user-images.githubusercontent.com/5672438/112942719-3c8d7900-9139-11eb-99dc-4e3342cb6f73.png)

2021-04-06 08:25 UTC, k8hughes commented
@edwinmp to review

2021-04-06 11:05 UTC, edwinmp commented
@ThatcherK I'm in the process of testing this on staging. Besides that, all that's left is to add documentation for it. The item on the dropdown should have a caption around the lines of `Duplicate a Step`
![image](https://user-images.githubusercontent.com/5672438/113701690-23f50400-96e1-11eb-99b8-5c886daa2dbf.png)

2021-04-07 14:53 UTC, edwinmp approved these changes

2021-04-07 14:54 UTC, merged