Feature/enable rest api
devinit/ddw-analyst-ui pull request #59
Opened 2019-03-05 16:24 UTC by akmiller01

Dependent on #58 since all authenticated models require a user field. Enables REST api endpoints for viewing Tags and Users.

E.g. `/api/users`
![image](https://user-images.githubusercontent.com/2836840/53819849-bb9f2b80-3f38-11e9-816b-8de86c47e254.png)

`/api/users/1`
![image](https://user-images.githubusercontent.com/2836840/53819939-e6897f80-3f38-11e9-9a12-766807f0f4ff.png)

`/api/tags/`
![image](https://user-images.githubusercontent.com/2836840/53820001-01f48a80-3f39-11e9-842a-ac06d62e30d7.png)

And authentication as demonstrated in the command line:
```
~$ http DELETE http://127.0.0.1:8000/api/tags/1/
HTTP/1.1 403 Forbidden
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Length: 63
Content-Type: application/json
Date: Tue, 05 Mar 2019 16:08:22 GMT
Server: WSGIServer/0.2 CPython/3.6.7
Vary: Accept
X-Frame-Options: SAMEORIGIN

{
    "detail": "You do not have permission to perform this action."
}
```
```
http -a alex:*********** DELETE http://127.0.0.1:8000/api/tags/1/
HTTP/1.1 204 No Content
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Length: 0
Date: Tue, 05 Mar 2019 16:08:50 GMT
Server: WSGIServer/0.2 CPython/3.6.7
Vary: Accept
X-Frame-Options: SAMEORIGIN
```

Needs tests.

2019-03-05 16:35 UTC, edwinmp commented
@akmiller01 I hope all these endpoints are built to require an API token. They shouldn't work without it, not even for fetching data.

2019-03-05 16:37 UTC, akmiller01 commented
Yep @edwinmp should be a simple change in settings.py https://github.com/devinit/ddw-analyst-ui/pull/59/files#diff-1e3260587452284432a23f27fe15da83R52

2019-03-05 18:08 UTC, akmiller01 commented
Coded up all of the Source related models and added them to a nested field serializer for you @edwinmp, hopefully this will be all you need to get started on the frontend source work.

Here's an e.g. of the nested fields on the Source List:
![image](https://user-images.githubusercontent.com/2836840/53826802-8d751800-3f47-11e9-8c0e-b701f87e39a8.png)

With `sourcecolumnmap_set` and `updatehistory_set` being nested.

And here's an e.g. of the User endpoint now:
![image](https://user-images.githubusercontent.com/2836840/53826914-b85f6c00-3f47-11e9-99a2-13485e3b59fd.png)

2019-03-06 09:29 UTC, edwinmp requested changes
Good. Could you add support for PUT & DELETE, cos we're going to have to perform all CRUD operations from the FE via the API.

2019-03-06 09:29 UTC, edwinmp commented on core/serializers.py
> +        fields = ('source', 'history_table', 'is_major_release', 'released_on', 'release_description', 'invalidated_on', 'invalidation_description')
Long line... could you move each option to it's own line. More readable. There's a JS/TS linter rule to keep the line length to max 120.

2019-03-06 09:29 UTC, edwinmp commented on core/serializers.py
> +        fields = ('indicator', 'indicator_acronym', 'source', 'source_acronym', 'source_url', 'download_path', 'last_updated_on', 'storage_type', 'active_mirror_name', 'description', 'user', 'created
This one is even longer...

2019-03-06 09:29 UTC, edwinmp commented on core/urls.py
> +    path(r'rest/', include('rest_framework.urls')),
As far as I can tell, this one adds login & logout urls for the DRF. Do we need those? When I logged in, I got the error below

![image](https://user-images.githubusercontent.com/5672438/53869458-5a935880-4009-11e9-8326-b884c10bab5e.png)

2019-03-06 09:29 UTC, edwinmp commented on core/urls.py
> +    path('sourcess/<int:pk>/', core_views.SourceDetail.as_view()),
`sources` ... typo

2019-03-06 09:29 UTC, edwinmp commented on core/views.py
> +    authentication_classes = [BasicAuthentication]
Change all these to use `TokenAuthentication`... can't be entering user credentials for every request.

`from knox.auth import TokenAuthentication`

2019-03-06 09:33 UTC, edwinmp requested changes

2019-03-06 09:33 UTC, edwinmp commented on core/serializers.py
> +        fields = ('name', 'user', 'created_on', 'updated_on')
Add the `id` field as well.

2019-03-06 09:33 UTC, edwinmp commented on core/serializers.py
> +        fields = ('source', 'name', 'description', 'source_name')
Here too.

2019-03-06 09:33 UTC, edwinmp commented on core/serializers.py
> +        fields = ('indicator', 'indicator_acronym', 'source', 'source_acronym', 'source_url', 'download_path', 'last_updated_on', 'storage_type', 'active_mirror_name', 'description', 'user', 'created
Add `id` here as well.

2019-03-06 13:01 UTC, akmiller01 commented on core/permissions.py
> +        # Write permissions are only allowed to the owner of the snippet.
Hey @edwinmp , I couldn't reply to your top review, but PUT and DELETE are allowed at the `Detail` level by owners right now. I'll add it for superusers as well.

2019-03-06 13:01 UTC, akmiller01 commented on core/permissions.py
> +
Python linting requires 2 newlines before a Class.

2019-03-06 13:24 UTC, akmiller01 commented
Okay, so removing the REST Framework urls has removed the login button from the View GUI. Is that what we want? 
![image](https://user-images.githubusercontent.com/2836840/53884274-36c01a80-3fe9-11e9-815a-c1053267dca9.png)

2019-03-06 13:25 UTC, akmiller01 commented
Also @edwinmp I saw you setup `/api/auth/login` View with `BasicAuthentication`. Do you want to change that to Token as well?

2019-03-06 13:28 UTC, edwinmp commented
@akmiller01 while the View GUI looks good, we have no intention of using it. I suggest you use a nice rest client like `Postman`.

As for the `/api/auth/login`, this is the only path that should require basic authentication. It returns the token that's used in all other API requests.

2019-03-06 13:29 UTC, edwinmp commented on core/permissions.py
> +
Ah, so it seems... had never noticed before.

2019-03-06 13:36 UTC, Napho commented
@akmiller01  from what i understand from @edwinmp , we need to use JWT. Might require additional models. Please make the push and i can look at that

2019-03-06 20:28 UTC, edwinmp approved these changes

2019-03-06 20:34 UTC, merged