Frozen data sets split from source data in the data sources view
devinit/ddw-analyst-ui pull request #692
Opened 2022-05-13 12:12 UTC by wakibi

2022-05-17 05:31 UTC, davidebukali reviewed
LGTM!

2022-05-17 06:41 UTC, edwinmp approved these changes, later dismissed
Looks good ... Deploy a beta to staging to test

2022-05-17 06:45 UTC, edwinmp commented
@wakibi Your super long branch names won't likely catch on ... I don't think branch names need to be sentences to make sense ... if u want details, read the PR title/description hehe

2022-05-18 08:00 UTC, edwinmp requested changes
Don't think the BE changes where worth it here ... frozen data sources are too few (and soon to be policed) that a FE filter would have sufficed, as we'd agreed. Would have been a lot less code.

2022-05-18 08:00 UTC, edwinmp commented on frontend/src/components/SourcesTableCard/SourcesTableCard.tsx
> +    { key: 'non-frozen', text: 'Non-frozen Sources', value: 0 },
Rename this `Core Sources` or something that's not `non-frozen` :)

2022-05-18 08:18 UTC, wakibi commented
> 

That's correct, and was my plan originally. I just thought it would give the wrong impression on the paginator when I started implementing, since the sources are fetched in batches of 20, and the count is got from the API as well. It would have made sense if we were fetching all sources at once. Your thoughts?

2022-05-18 08:21 UTC, edwinmp commented
> > 
> 
> That's correct, and was my plan originally. I just thought it would give the wrong impression on the paginator when I started implementing, since the sources are fetched in batches of 20, and the count is got from the API as well. It would have made sense if we were fetching all sources at once. Your thoughts?

Oh, I'd not accounted for the `paginator` ... you're absolutely right ... let's keep it as is.

2022-05-18 08:52 UTC, edwinmp approved these changes

2022-05-18 09:16 UTC, merged