Feature | Change Help icon to a button that says User guide
devinit/ddw-analyst-ui pull request #701
Opened 2022-05-21 10:44 UTC by pauline-n

#664

2022-05-23 07:41 UTC, ThatcherK requested changes

2022-05-23 07:41 UTC, ThatcherK commented on frontend/src/components/Help/HelpNavItem.tsx
>          <p className="d-lg-none d-md-block">Help</p>
This line is no longer needed, remove..

2022-05-23 07:45 UTC, edwinmp requested changes

2022-05-23 07:45 UTC, edwinmp commented on frontend/src/components/Help/HelpNavItem.tsx
> +import { Button } from 'semantic-ui-react';
Unless the component you need doesn't exist in Bootstrap, always use Bootstrap components, not Semantic UI.

2022-05-23 08:51 UTC, pauline-n commented
<img width="1428" alt="Screenshot 2022-05-23 at 11 47 00" src="https://user-images.githubusercontent.com/71310090/169781566-82546bc7-a0ab-4f11-b7e1-a37ef648add8.png">
@edwinmp @ThatcherK This is how it looks like

2022-05-23 08:56 UTC, edwinmp commented
@pauline-n it's too big and it has a dropdown arrow beside it. Give it the class `btn-sm`

2022-05-23 09:41 UTC, pauline-n commented
<img width="703" alt="Screenshot 2022-05-23 at 12 39 20" src="https://user-images.githubusercontent.com/71310090/169791318-24616e65-107d-42c2-aa56-20696cde146f.png">
Not sure if you had also meant, remove the dropdown beside it?

2022-05-23 13:18 UTC, edwinmp requested changes
Add an updated photo.

2022-05-23 13:18 UTC, edwinmp commented on frontend/src/components/Help/HelpNavItem.tsx
> +        <Button variant="btn-secondary" className="btn-secondary" size="sm">
Incorrect variant ... I'm pretty sure this should result in an error.
```suggestion
        <Button variant="secondary" size="sm">
```

2022-05-23 13:20 UTC, edwinmp commented
> <img alt="Screenshot 2022-05-23 at 12 39 20" width="703" src="https://user-images.githubusercontent.com/71310090/169791318-24616e65-107d-42c2-aa56-20696cde146f.png">
> 
> Not sure if you had also meant, remove the dropdown beside it?

Ofc ... can't see any other dropdown arrow. This button is not a dropdown so it shouldn't have a little arrow that should only be on dropdowns.

2022-05-24 08:00 UTC, pauline-n commented
<img width="1384" alt="Screenshot 2022-05-24 at 10 57 59" src="https://user-images.githubusercontent.com/71310090/169980299-a09410a8-730d-43b5-9401-b20275466eb1.png">
updated photo

2022-05-24 08:00 UTC, pauline-n commented
<img width="1384" alt="Screenshot 2022-05-24 at 10 58 17" src="https://user-images.githubusercontent.com/71310090/169980401-ddbb288c-088b-4171-ad49-1c96dc402bd2.png">
How it appears when you click on the button user guide

2022-05-25 09:26 UTC, edwinmp approved these changes

2022-05-25 09:27 UTC, merged