Use a configured base URL
devinit/ddw-analyst-ui pull request #962
Opened 2023-07-21 12:43 UTC by APIYOJENNIFER

Issue #688 
- Use a configured base URL to be able to test API endpoints in different environments

2023-07-24 06:54 UTC, ThatcherK requested changes

2023-07-24 06:54 UTC, ThatcherK commented on frontend/src/utils/api.ts
> +import config from '../config';
I don't expect any changes in this file

2023-07-24 06:54 UTC, ThatcherK commented on frontend/src/config.ts
> +const config: { BASE_URL: string } = {
This is not an environment variable..
I expect an axios config, and then the config takes in an environment variable as the baseUrl

2023-07-26 12:18 UTC, ThatcherK requested changes

2023-07-26 12:18 UTC, ThatcherK commented on frontend/src/config.ts
> +const axiosConfig = axios.create({
This config does not seem to be referenced anywhere else apart from this file. So I doubt it's working...
Please see if [this](https://bobbyhadz.com/blog/axios-change-base-url#:~:text=%23%20Setting%20the%20axios%20Base%20URL%20by%20creating%20an%20instance,'%2C%20%7D)%3B%20placeholderApi%20.) resource helps

2023-07-27 06:06 UTC, ThatcherK requested changes
Much as this might work, I would rather you add the baseUrl in the index.js file which doesnt require you to add it to all places where axios is called. Less code. Sometrhing similar to this 
`axios.defaults.baseURL` that sets it as a global baseUrl for all axios calls. Also make sure you r environment variable is actually being read as what you have set...

2023-07-27 10:24 UTC, ThatcherK requested changes

2023-07-27 10:24 UTC, ThatcherK commented on frontend/src/index.ts
> +axios.defaults.baseURL = process.env.BASE_URL;
As I sort my testing issues,move this to the App.ts file, I've seen most configs are initialised there. Let's leave the index file as clean as we found it!.. Also test that it still works

2023-07-27 10:28 UTC, ThatcherK commented on frontend/src/index.ts
> +axios.defaults.baseURL = process.env.BASE_URL;
You will also need to add it to the docker_compose files. Check the environment section of the web service.
Then also add it to the readme as a variable that needs to be set

2023-07-28 06:56 UTC, ThatcherK commented
@davidebukali can you test that this works, am unable to test on my end

2023-07-31 13:59 UTC, ThatcherK reviewed
Waiting to properly test before merging

2023-08-02 12:58 UTC, davidebukali commented
@ThatcherK this looks good to me

2023-08-14 10:51 UTC, ThatcherK approved these changes

2023-08-14 10:51 UTC, merged